---
dependencies:
  - { role: "azavea.python", python_development: True }
  - { role: "azavea.pip" }
  - { role: "azavea.postgresql-support" }
  - { role: "azavea.ruby" }
  - { role: "azavea.phantomjs" }
  - { role: "azavea.sauce-connect", when: sauce_labs_api_key_is_defined }
  - { role: "nyc-trees.monitoring", collectd_prefix: "collectd.app.", when: "['test'] | is_not_in(group_names)" }
  - { role: "nyc-trees.celery" }
  - { role: "azavea.swapfile", when: "['development', 'test'] | some_are_in(group_names)" }
