---
- name: Check if Puppet service definition exists
  stat: path=/etc/init.d/puppet
  register: puppet_installed

- name: Stop Puppet service
  service: name=puppet state=stopped
  when: puppet_installed.stat.exists and developing_or_testing

- name: Remove Puppet service
  file: path=/etc/init.d/puppet state=absent
  when: puppet_installed.stat.exists and developing_or_testing

- name: Check if Chef service definition exists
  stat: path=/etc/init.d/chef-client
  register: chef_installed

- name: Stop Chef service
  service: name=chef-client state=stopped
  when: chef_installed.stat.exists and developing_or_testing

- name: Remove Chef service
  file: path=/etc/init.d/chef-client state=absent
  when: chef_installed.stat.exists and developing_or_testing
