---
- name: Create service account for application
  user: name=nyc-trees
        system=yes
        home=/var/lib/nyc-trees
        shell=/bin/false
        state=present

- name: Add Vagrant user to the nyc-trees group
  user: name=vagrant
        append=yes
        group=nyc-trees
        state=present
  when: developing_or_testing

- name: Create configuration file directory
  file: path={{ app_config_home }}
        owner=root
        group=nyc-trees
        mode=0750
        state=directory

- name: Configure application
  copy: content={{ item.content }}
        dest={{ app_config_home }}/{{ item.file }}
        owner=root
        group=nyc-trees
        mode=0750
  with_items: app_config

- name: Configure Sauce Labs settings
  copy: content={{ item.content }}
        dest={{ app_config_home }}/{{ item.file }}
        owner=root
        group=nyc-trees
        mode=0750
  with_items: app_sauce_labs_config
  when: sauce_labs_api_key_is_defined
