---
- name: Touch log file if it does not exist
  command: touch {{ app_log }}
           creates={{ app_log }}

- name: Set log file permissions
  file: path={{ app_log }} owner=nyc-trees group=nyc-trees mode=0644

- name: Configure Gunicorn log rotation
  template: src=logrotate-nyc-trees-app.j2 dest=/etc/logrotate.d/nyc-trees-app
