---
- hosts: services
  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "nyc-trees.common" }

    - { role: "azavea.postgresql" }
    - { role: "azavea.redis" }
    - { role: "azavea.kibana" }
    - { role: "nyc-trees.logstash" }
    - { role: "nyc-trees.graphite" }
