---
- hosts: tile-servers
  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "nyc-trees.common" }

    - { role: "azavea.nodejs" }
    - { role: "azavea.mapnik" }
